---
layout: page
title: EDA
output:
  html_document:
    theme: default
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_sections: TRUE
---

# Load Data
```{r}
library(tidyverse)
library(lubridate)

act_info = read.csv('./Raw_Data/2_act_info.csv') # 계좌번호 / 고객번호 / 계좌개설월
cus_info = read.csv('./Raw_Data/2_cus_info.csv') # 고객번호 / 성별 / 연령대 / 주소 / 고객등급 / 고객투자성향
iem_info = read.csv('./Raw_Data/2_iem_info.csv') # 종목코드 / 종목영문명 / 종목한글명
trd_kr = read.csv('./Raw_Data/2_trd_kr.csv') # 계좌번호 / 주문날짜 / 주문순서 / 주문접수시간대 / 최종체결시간대 / 종목코드 / 매매구분코드 / 체결수량 / 체결가격 / 주문매체구분코드
trd_oss = read.csv('./Raw_Data/2_trd_oss.csv') # 계좌번호 / 주문날짜 / 주문순서 / 주문접수시간대 / 최종체결시간대 / 종목코드 / 매매구분코드 / 체결수량 / 체결가격 / 주문매체구분코드 / 거래통화코드 / 거래통화환율
```

# Missing Value Detection
```{r}
colSums(is.na(act_info))
colSums(is.na(cus_info))
colSums(is.na(iem_info))
colSums(is.na(trd_kr))
colSums(is.na(trd_oss))
```

# EDA
## act_info
```{r}
library(ggplot2)

length(unique(act_info$cus_id)) # 정확히 10,000명의 고객에 대한 데이터

act_info_by_cus = act_info %>%
  group_by(cus_id) %>%
  summarize(n=n())

ggplot(act_info_by_cus, aes(n)) + geom_histogram() # 대부분 1~2개 이내의 계좌 사용
```

## cus_info
```{r}
ggplot(cus_info, aes(sex_dit_cd)) + geom_bar(stat='count') # 남성 고객이 여성 고객의 약 1.5배
ggplot(cus_info, aes(cus_age)) + geom_bar(stat='count') # 0이 결측치로 추정, 5세 단위
ggplot(cus_info, aes(zip_ctp_cd)) + geom_bar(stat='count') # -가 결측치로 추정, 대부분 서울, 경기
ggplot(cus_info, aes(tco_cus_grd_cd)) + geom_bar(stat='count') # -가 결측치로 추정, 피라미드 구조
ggplot(cus_info, aes(ivs_icn_cd)) + geom_bar(stat='count') # -가 결측치로 추정, 대부분 결측치
```

## trd_kr
```{R}
trd_kr = trd_kr %>%
  mutate(orr_dt=ymd(orr_dt))

ggplot(trd_kr, aes(orr_rtn_hur)) + geom_bar(stat='count') # 9시가 가장 많음
ggplot(trd_kr, aes(lst_cns_hur)) + geom_bar(stat='count') # 주문접수시간대와 거의 일치
ggplot(trd_kr, aes(sby_dit_cd)) + geom_bar(stat='count') # 매수가 매도의 약 2배
ggplot(trd_kr, aes(orr_mdi_dit_cd)) + geom_bar(stat='count') # 대부분 무선단말MTS
ggplot(trd_kr, aes(orr_pr)) + geom_histogram() + scale_x_log10()

trd_kr_by_act = trd_kr %>%
  group_by(act_id) %>%
  summarize(orr_cnt=n())

ggplot(trd_kr_by_act, aes(orr_cnt)) + geom_histogram() # 대부분 100회 미만

trd_kr_by_dt = trd_kr %>%
  group_by(orr_dt) %>%
  summarize(orr_cnt=n())

ggplot(trd_kr_by_dt, aes(x=orr_dt, y=orr_cnt)) + geom_line() # 19년 1월 ~ 20년 6월까지의 데이터, 20년 이후 거래 횟수 급증
```

## trd_oss
```{r}
trd_oss = trd_oss %>%
  mutate(orr_dt=ymd(orr_dt))

ggplot(trd_oss, aes(orr_rtn_hur)) + geom_bar(stat='count') # 22~23시가 가장 많음
ggplot(trd_oss, aes(lst_cns_hur)) + geom_bar(stat='count') # 주문접수시간대와 거의 일치
ggplot(trd_oss, aes(sby_dit_cd)) + geom_bar(stat='count') # 매수가 매도의 약 3배
ggplot(trd_oss, aes(orr_mdi_dit_cd)) + geom_bar(stat='count') # 대부분 무선단말
ggplot(trd_oss, aes(orr_pr)) + geom_histogram() + scale_x_log10()
ggplot(trd_oss, aes(cur_cd)) + geom_bar(stat='count') # 대부분 달러화

trd_oss_by_act = trd_oss %>%
  group_by(act_id) %>%
  summarize(orr_cnt=n())

ggplot(trd_oss_by_act, aes(orr_cnt)) + geom_histogram() # 대부분 100회 미만

trd_oss_by_dt = trd_oss %>%
  group_by(orr_dt) %>%
  summarize(orr_cnt=n())

ggplot(trd_oss_by_dt, aes(x=orr_dt, y=orr_cnt)) + geom_line() # 19년 1월 ~ 20년 6월까지의 데이터, 20년 이후 거래 횟수 급증
```